// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables
if (!SUPABASE_URL) {
  console.error('❌ VITE_SUPABASE_URL is not set in environment variables');
  console.error('   Please add VITE_SUPABASE_URL to your .env file');
  throw new Error('Supabase URL is required. Check your .env file and restart the dev server.');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ VITE_SUPABASE_PUBLISHABLE_KEY is not set in environment variables');
  console.error('   Please add VITE_SUPABASE_PUBLISHABLE_KEY to your .env file');
  throw new Error('Supabase publishable key is required. Check your .env file and restart the dev server.');
}

console.log('✅ Supabase configuration loaded');
console.log(`   URL: ${SUPABASE_URL}`);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY || SUPABASE_ANON_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
    global: {
      headers: {
        'Content-Type': 'application/json',
      },
      fetch: (...args) => {
        return fetch(...args).catch((error) => {
          console.error('Supabase fetch error:', error);
          throw error;
        });
      },
    },
  }
);

// Monitor auth changes
supabase.auth.onAuthStateChange((event, session) => {
  console.log(`🔐 Auth state changed: ${event}`, session?.user?.email);
});